package render

import (
	"fmt"
	"io"
	"strings"
	"text/template"

	"github.com/Xiuyixx/5GPN-Go/internal/config"
)

// DnsdistRenderer materializes dnsdist.conf (Lua) from a Config.
//
// The template mirrors the semantics of 5GPN-X/dnsdist.conf.template:
// DoT + classic 53 listeners, china/remote pools, per-IP QPS cap,
// AAAA NODATA, ChinaList vs default routing. The template scaffolds
// the pieces install.sh used to sed-substitute (__REMOTE_DNS_SERVERS__,
// __GFWLIST_RULES__, __CHINALIST_RULES__) as first-class fields.
type DnsdistRenderer struct{}

const defaultChinaListPath = "/var/lib/5gpn/chinalist.txt"

// Render writes the dnsdist.conf equivalent of cfg to w.
func (DnsdistRenderer) Render(cfg *config.Config, w io.Writer) error {
	if cfg == nil {
		return fmt.Errorf("dnsdist: nil config")
	}
	upstreams := cfg.DNS.Upstreams
	if len(upstreams) == 0 {
		upstreams = []string{"1.1.1.1:53", "8.8.8.8:53"}
	}
	remoteBlock := &strings.Builder{}
	for i, u := range upstreams {
		host, port := splitHostPort(u, "53")
		fmt.Fprintf(remoteBlock,
			"newServer({address=%q, pool=%q, name=%q, order=%d})\n",
			host+":"+port, "remote", fmt.Sprintf("remote_%d", i+1), i+2)
	}
	chinaListPath := cfg.DNS.ChinaListPath
	if chinaListPath == "" {
		chinaListPath = defaultChinaListPath
	}
	data := struct {
		Domain            string
		Cert              string
		Key               string
		DoTPort           int
		Upstreams         string
		ChinaListPath     string
		ChinaListPathQuot string // Lua-quoted path for io.lines calls
	}{
		Domain:            cfg.Server.Domain,
		Cert:              firstNonEmpty(cfg.Server.TLS.Cert, "/etc/dnsdist/certs/fullchain.pem"),
		Key:               firstNonEmpty(cfg.Server.TLS.Key, "/etc/dnsdist/certs/privkey.pem"),
		DoTPort:           firstNonZero(cfg.DNS.DoTPort, 853),
		Upstreams:         remoteBlock.String(),
		ChinaListPath:     chinaListPath,
		ChinaListPathQuot: fmt.Sprintf("%q", chinaListPath),
	}
	return dnsdistTemplate.Execute(w, data)
}

var dnsdistTemplate = template.Must(template.New("dnsdist").Parse(`-- Auto-generated by 5gpn — do not hand-edit.
setServerPolicy(leastOutstanding)
addLocal("0.0.0.0:53", {doTCP=true})

-- DoT listener
certPath = "{{ .Cert }}"
keyPath  = "{{ .Key }}"
addTLSLocal("0.0.0.0:{{ .DoTPort }}", certPath, keyPath, {
    provider="openssl",
    sessionTickets=true,
    sessionTimeout=3600
})

-- China DNS pool (served by internal race proxy on 127.0.0.1:5301)
newServer({address="127.0.0.1:5301", pool="china", name="china_dns_race", order=1, useClientSubnet=true})

-- Remote DNS pool
{{ .Upstreams }}
-- ACL: NPN client network gets full service, others only DoT.
setACL({"0.0.0.0/0", "::/0"})
privateClientRule = makeRule({"172.22.0.0/16"})
nonPrivateClientRule = NotRule(privateClientRule)
addAction(AndRule({nonPrivateClientRule, DSTPortRule(53)}), DropAction())

-- Rate limit per client IP (drop above 10k qps)
addAction(MaxQPSIPRule(10000), DropAction())

-- IPv4-only: return NODATA for AAAA queries.
addAction(QTypeRule(DNSQType.AAAA), RCodeAction(DNSRCode.NOERROR))

-- ChinaList domains -> china pool (source: {{ .ChinaListPath }})
local chinaList = newSuffixMatchNode()
pcall(function()
    for line in io.lines({{ .ChinaListPathQuot }}) do
        local trimmed = line:match("^%s*(.-)%s*$")
        if trimmed ~= "" and trimmed:sub(1,1) ~= "#" then
            chinaList:add(newDNSName(trimmed))
        end
    end
end)
if not pcall(io.lines, {{ .ChinaListPathQuot }}) then
    warnlog("5gpn: chinalist file not found or unreadable: {{ .ChinaListPath }}")
end

-- Everything else -> remote pool
addAction(SuffixMatchNodeRule(chinaList), PoolAction("china"))
addAction(AllRule(), PoolAction("remote"))
`))

func splitHostPort(hp, defaultPort string) (host, port string) {
	if i := strings.LastIndex(hp, ":"); i > 0 && !strings.HasSuffix(hp, "]") {
		return hp[:i], hp[i+1:]
	}
	return hp, defaultPort
}

func firstNonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func firstNonZero(a, b int) int {
	if a != 0 {
		return a
	}
	return b
}
