package render

import (
	"fmt"
	"io"
	"strings"
	"text/template"

	"github.com/Xiuyixx/5GPN-Go/internal/config"
)

// SniproxyRenderer materializes sniproxy.conf.
//
// Preserves the shape of 5GPN-X/sniproxy.conf: a dedicated pxout user,
// syslog error log, resolver block (populated from cfg.DNS.Upstreams),
// HTTP :80 + loopback-only HTTPS :8443 backends. wa-shim owns the
// public :443 upstream in front of the loopback backend.
type SniproxyRenderer struct{}

// Render writes the sniproxy.conf equivalent of cfg to w.
func (SniproxyRenderer) Render(cfg *config.Config, w io.Writer) error {
	if cfg == nil {
		return fmt.Errorf("sniproxy: nil config")
	}
	upstreams := cfg.DNS.Upstreams
	if len(upstreams) == 0 {
		upstreams = []string{"1.1.1.1", "8.8.8.8"}
	}
	nsBlock := &strings.Builder{}
	for _, u := range upstreams {
		host, _ := splitHostPort(u, "53")
		fmt.Fprintf(nsBlock, "    nameserver %s\n", host)
	}

	loopback := firstNonZero(cfg.Proxy.SniProxy.LoopbackHTTPS, 8443)
	http := firstNonZero(cfg.Proxy.SniProxy.ListenHTTP, 80)

	return sniproxyTemplate.Execute(w, struct {
		Nameservers   string
		ListenHTTP    int
		LoopbackHTTPS int
	}{
		Nameservers:   nsBlock.String(),
		ListenHTTP:    http,
		LoopbackHTTPS: loopback,
	})
}

var sniproxyTemplate = template.Must(template.New("sniproxy").Parse(`# Auto-generated by 5gpn — do not hand-edit.
user pxout
pidfile /var/run/sniproxy.pid

resolver {
{{ .Nameservers }}    mode ipv4_only
}

error_log {
    syslog daemon
    priority notice
}

listener 0.0.0.0:{{ .ListenHTTP }} {
    protocol http
    table http_hosts
}

# wa-shim owns public TCP/443 and fails open to this loopback backend.
listener 127.0.0.1:{{ .LoopbackHTTPS }} {
    protocol tls
    table tls_hosts
}

table http_hosts {
    .* *:80
}

table tls_hosts {
    .* *:443
}
`))
